name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:

permissions:
  checks: read
  contents: read

jobs:
  install-deps:
    if: ${{ github.event.action != 'edited' }}
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install locked dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            node_modules
          key: ${{ github.sha }}

  test-unit:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: restore-deps
        with:
          path: node_modules
          key: ${{ github.sha }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Run tests
        run: "npm run test -- --ci"
        env:
          CI: "true"
